# Generated by Django 4.2.3 on 2024-10-12 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart_app', '0004_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='address',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='city',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='state',
        ),
    ]
