# Generated by Django 4.2.3 on 2024-10-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart_app', '0006_remove_product_created_at_remove_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
